CREATE TABLE [dbo].[Tarea]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	[Nombre] VARCHAR(MAX) NOT NULL,
	[Descripcion] VARCHAR(MAX) NOT NULL,
	[FechaInicio] Date NOT NULL,
	[FechaFinal] Date NOT NULL,
	[Asignado] UNIQUEIDENTIFIER NOT NULL,
	[Estado] UNIQUEIDENTIFIER NOT NULL,
	[Creador] UNIQUEIDENTIFIER NOT NULL

)
